version: "3"
services:
  elasticsearch_practice:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    container_name: elasticsearch_practice
    environment:
      - bootstrap.memory_lock=true  # Locks memory to improve performance and prevent swapping.
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Sets heap size to 512 MB for Elasticsearch.
      - "discovery.type=single-node"  # Configures node as a single node cluster.
      - xpack.security.enabled=false  # Disables security features in Elasticsearch.
    ports:
      - "9200:9200"  # Exposes port 9200 for accessing Elasticsearch.
    volumes:
      - elasticsearch_practice_data:/usr/share/elasticsearch/data  # Persists data using a named volume.
    networks:
      - elasticsearch_practice

  kibana_practice:
    image: docker.elastic.co/kibana/kibana:8.3.3
    container_name: kibana_practice
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch_practice:9200"]'  # URL for Kibana to connect to Elasticsearch.
    depends_on:
      - elasticsearch_practice
    networks:
      - elasticsearch_practice

networks:
  elasticsearch_practice:
    driver: bridge  # Uses bridge driver for an isolated network environment.

volumes:
  elasticsearch_practice_data:
    driver: local  # Uses local driver for storing data.